targets:
  $default:
    builders:
      source_gen|combining_builder:
        enabled: true

builders:
  data_monitor:
    import: 'package:data_monitor_generators/data_monitor_generators.dart'
    builder_factories: [ 'generateBuilders' ]
    build_extensions: { '.dart': ['data_monitor.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ 'source_gen|combining_builder' ]
